# Generated by Django 6.0.4 on 2026-04-20 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_protect_supplier_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Exemples : +241 07 40 13 02, 074013 02.', regex='^\\+?[\\d\\s\\-().]{6,20}$')]),
        ),
    ]
