# Generated by Django 6.0.4 on 2026-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Liste des permissions accordées à cet utilisateur'),
        ),
    ]
