# Generated by Django 6.0.4 on 2026-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_last_seen_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Monsieur'), ('F', 'Madame')], max_length=1, null=True),
        ),
    ]
