from django.db import transaction
from rest_framework import viewsets, generics, filters
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from django_filters.rest_framework import DjangoFilterBackend

from .models import Sale, SaleItem
from .serializers import SaleCreateSerializer, SaleSerializer
from products.models import Product
from stock.models import StockMovement
from invoices.models import Invoice


class SaleViewSet(viewsets.ReadOnlyModelViewSet):
    """
    List and retrieve sales.
    Supports filtering by payment_method, cashier, client.
    Ordered by most recent first.
    """
    queryset = Sale.objects.select_related('client', 'cashier').prefetch_related(
        'items__product'
    )
    serializer_class = SaleSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    filterset_fields = ['payment_method', 'cashier', 'client']
    ordering = ['-created_at']


class CreateSaleView(generics.CreateAPIView):
    """
    Atomically: validate stock -> decrement stock -> create Sale ->
    create SaleItems -> create StockMovements -> create Invoice.
    """
    serializer_class = SaleCreateSerializer
    permission_classes = [IsAuthenticated]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data

        with transaction.atomic():
            # 1. Create Sale
            sale = Sale.objects.create(
                cashier=request.user,
                client_id=data.get('client_id'),
                total_amount=data['total_amount'],
                amount_paid=data['amount_paid'],
                change_given=data['change_given'],
                payment_method=data['payment_method'],
                note=data.get('note', ''),
            )

            # 2. Create SaleItems + decrement stock + record movements
            for item_data in data['items']:
                product = Product.objects.select_related('stock').get(
                    pk=item_data['product_id']
                )
                SaleItem.objects.create(
                    sale=sale,
                    product=product,
                    quantity=item_data['quantity'],
                    unit_price=item_data['unit_price'],
                )
                stock = product.stock
                qty_before = stock.quantity
                stock.quantity -= item_data['quantity']
                stock.save()
                StockMovement.objects.create(
                    product=product,
                    movement_type='sale',
                    quantity=-item_data['quantity'],
                    quantity_before=qty_before,
                    quantity_after=stock.quantity,
                    note=f'Vente #{sale.pk}',
                    performed_by=request.user,
                )

            # 3. Create Invoice (invoice_number auto-generated by model.save)
            Invoice.objects.create(
                sale=sale,
                client=sale.client,
                total_amount=sale.total_amount,
                amount_paid=sale.amount_paid,
                status='paid',
                issued_by=request.user,
            )

        return Response(
            SaleSerializer(sale).data,
            status=status.HTTP_201_CREATED,
        )
