# Generated by Django 6.0.4 on 2026-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de taxe (%)')),
                ('currency', models.CharField(default='FCFA', max_length=8, verbose_name='Devise')),
                ('ticket_footer', models.TextField(blank=True, default='', verbose_name='Pied de ticket')),
                ('invoice_prefix', models.CharField(default='FAC', max_length=16, verbose_name='Préfixe facture')),
                ('default_payment_method', models.CharField(default='cash', max_length=20, verbose_name='Méthode de paiement par défaut')),
            ],
            options={
                'verbose_name': 'Paramètres POS',
                'verbose_name_plural': 'Paramètres POS',
            },
        ),
    ]
