# Generated by Django 6.0.4 on 2026-04-16 19:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NAOSERVICES', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Libreville', max_length=100)),
                ('country', models.CharField(default='Gabon', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nif', models.CharField(blank=True, help_text="Numéro d'identifiant fiscal", max_length=50)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('invoice_footer', models.TextField(blank=True)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprise',
            },
        ),
    ]
